import type { ConceptNode, Graph } from "@nodestorm/shared";
import { describe, expect, it } from "vitest";
import { buildExample, EXAMPLES } from "../src/lib/examples";
import * as ops from "../src/lib/graphOps";
import { labels, texEscape, texEscapeText, toLatex } from "../src/lib/latex";

/** Every \begin{x} is closed by a matching \end{x}, properly nested. */
function balanced(tex: string): boolean {
  const stack: string[] = [];
  for (const m of tex.matchAll(/\\(begin|end)\{([^}]+)\}/g)) {
    if (m[1] === "begin") stack.push(m[2]);
    else if (stack.pop() !== m[2]) return false;
  }
  return stack.length === 0;
}

/** Braces balance outside escaped ones (\{ \}). */
function bracesBalance(tex: string): boolean {
  let depth = 0;
  const body = tex.replace(/\\[{}]/g, "").replace(/(^|[^\\])%.*$/gm, "$1");
  for (const c of body) {
    if (c === "{") depth++;
    else if (c === "}" && --depth < 0) return false;
  }
  return depth === 0;
}

const node = (id: string, name: string, patch: Partial<ConceptNode> = {}): ConceptNode => ({
  id, name, definition: "", aliases: [], status: "ok", position: { x: 0, y: 0 }, dependsOn: [], missingDeps: [], ...patch,
});

describe("texEscape", () => {
  it("escapes LaTeX's special characters in text", () => {
    expect(texEscapeText("50% of #1 & a_b {x} ~ ^ \\ $5")).toBe(
      "50\\% of \\#1 \\& a\\_b \\{x\\} \\textasciitilde{} \\textasciicircum{} \\textbackslash{} \\$5",
    );
    expect(texEscapeText("a < b > c | d")).toBe("a \\textless{} b \\textgreater{} c \\textbar{} d");
  });

  it("passes formulas through and escapes only the text around them", () => {
    expect(texEscape("If $a_1 \\in G$ & $x^2$ is 50%")).toBe("If $a_1 \\in G$ \\& $x^2$ is 50\\%");
    expect(texEscape("see \\(\\ker\\varphi\\) and $$G/N$$")).toBe("see $\\ker\\varphi$ and \\[ G/N \\]");
    // An unbalanced dollar is text (money), as the app reads it.
    expect(texEscape("costs $5 each")).toBe("costs \\$5 each");
  });

  it("writes common Unicode math symbols and Greek letters as LaTeX", () => {
    expect(texEscapeText("φ: G → H, x ≤ y")).toBe("\\ensuremath{\\varphi}: G \\ensuremath{\\to} H, x \\ensuremath{\\le} y");
    expect(texEscapeText("Poincaré")).toBe("Poincaré");
  });
});

describe("labels", () => {
  it("are slugs, unique, with a fallback for names without Latin letters", () => {
    const l = labels([node("a", "First Isomorphism Theorem"), node("b", "first isomorphism theorem!"), node("c", "群"), node("d", "Poincaré")]);
    expect([...l.values()]).toEqual(["c:first-isomorphism-theorem", "c:first-isomorphism-theorem-2", "c:concept-3", "c:poincare"]);
  });
});

describe("toLatex", () => {
  const example = () => buildExample(ops.emptyGraph("Group theory"), EXAMPLES.groupTheory);

  it("is a complete amsart document with balanced environments and braces", () => {
    const tex = toLatex(example(), { date: new Date("2026-09-24T12:00:00Z") });
    expect(tex).toMatch(/^% Generated by NodeStorm/);
    expect(tex).toContain("\\documentclass{amsart}");
    expect(tex).toContain("\\usepackage{amsmath,amssymb,amsthm}");
    expect(tex).toContain("\\title{Group theory}");
    expect(tex).toContain("\\date{2026-09-24}");
    expect(tex.trimEnd().endsWith("\\end{document}")).toBe(true);
    expect(balanced(tex)).toBe(true);
    expect(bracesBalance(tex)).toBe(true);
  });

  it("uses one environment per kind, prerequisites first, with cross-references", () => {
    const tex = toLatex(example());
    expect(tex).toContain("\\begin{definition}[{Group}]\\label{c:group}");
    expect(tex).toContain("\\begin{theorem}[{First Isomorphism Theorem}]\\label{c:first-isomorphism-theorem}");
    expect(tex.indexOf("\\label{c:group}")).toBeLessThan(tex.indexOf("\\label{c:subgroup}"));
    expect(tex.indexOf("\\label{c:kernel}")).toBeLessThan(tex.indexOf("\\label{c:first-isomorphism-theorem}"));
    const thm = tex.slice(tex.indexOf("\\begin{theorem}"), tex.indexOf("\\end{theorem}"));
    expect(thm).toContain("\\emph{Uses:} Definition~\\ref{c:homomorphism} (Homomorphism)");
    expect(thm).toContain("Definition~\\ref{c:kernel} (Kernel)");
    expect(thm).toContain("\\emph{Also needs (not in this graph):} Isomorphism.");
    // Formulas are kept as written.
    expect(thm).toContain("$\\varphi: G \\to H$");
    // Every \ref points at a \label.
    const defined = new Set([...tex.matchAll(/\\label\{([^}]+)\}/g)].map((m) => m[1]));
    for (const m of tex.matchAll(/\\ref\{([^}]+)\}/g)) expect(defined.has(m[1])).toBe(true);
  });

  it("untyped concepts are Concepts; notes become remarks; a proof idea becomes a proof sketch", () => {
    const g: Graph = {
      id: "g", name: "Notes & stuff", relations: [],
      nodes: [
        node("a", "Idea_1", { definition: "Costs 5% & more.\n\nSecond paragraph.", notes: "Check #3 in {book}." }),
        node("b", "Main result", {
          kind: "lemma", dependsOn: ["a"], definition: "If $x$ then $y$.",
          anatomy: { hypotheses: [], conclusion: "y", proofIdea: "Use $x$.", examples: [], nonExamples: [], createdAt: 1 },
        }),
        node("c", "Guess", {
          kind: "conjecture",
          anatomy: { hypotheses: [], conclusion: "z", proofIdea: "Checked up to $10^6$.", examples: [], nonExamples: [], createdAt: 1 },
        }),
      ],
    };
    const tex = toLatex(g);
    expect(tex).toContain("\\title{Notes \\& stuff}");
    expect(tex).toContain("\\begin{concept}[{Idea\\_1}]");
    expect(tex).toContain("Costs 5\\% \\& more.\n\nSecond paragraph.");
    expect(tex).toContain("\\begin{remark}[Notes]\nCheck \\#3 in \\{book\\}.\n\\end{remark}");
    expect(tex).toContain("\\emph{Uses:} Concept~\\ref{c:idea-1} (Idea\\_1).");
    expect(tex).toContain("\\begin{proof}[Proof idea]\nUse $x$.\n\\end{proof}");
    expect(tex).toContain("\\begin{remark}[Evidence]\nChecked up to $10^6$.\n\\end{remark}");
    expect(tex).toContain("\\begin{conjecture}[{Guess}]");
    expect(tex).toContain("\\emph{No statement yet.}");
    expect(balanced(tex)).toBe(true);
    expect(bracesBalance(tex)).toBe(true);
  });

  it("an empty graph is still a valid document; CJK text asks for xelatex", () => {
    const empty = toLatex(ops.emptyGraph());
    expect(empty).toContain("This graph has no concepts yet.");
    expect(balanced(empty)).toBe(true);
    expect(empty).not.toContain("xeCJK");
    const zh = toLatex({ ...ops.emptyGraph("群论"), nodes: [node("a", "群", { definition: "带有结合运算的集合。" })] });
    expect(zh).toContain("compile with xelatex");
    expect(zh).toContain("\\usepackage{xeCJK}");
  });
});

describe("toLatex: symbols, scripts and stale parts", () => {
  const graphWith = (patch: Partial<ConceptNode>) => {
    const r = ops.addNode(ops.emptyGraph("G"), { name: "X" });
    return ops.updateNode(r.graph, r.id, patch);
  };

  it("writes Unicode symbols inside formulas as commands, and escapes % there", () => {
    const tex = toLatex(graphWith({ definition: "A map $f: G → H$ with $a ≤ b$ and $x % y$ and $αx$." }));
    expect(tex).toContain("$f: G \\to H$");
    expect(tex).toContain("$a \\le b$");
    expect(tex).toContain("$x \\% y$");
    expect(tex).toContain("$\\alpha x$");
  });

  it("gives characters pdfLaTeX doesn't know a placeholder so the document compiles", () => {
    const tex = toLatex(graphWith({ definition: "Snowman ☃ here." }));
    expect(tex).toContain("\\DeclareUnicodeCharacter{2603}{\\ensuremath{\\square}}");
  });

  it("asks for xelatex when any part has CJK text, not only the definition", () => {
    const tex = toLatex(graphWith({ aliases: ["群"] }));
    expect(tex).toContain("compile with xelatex");
    expect(tex).toContain("\\usepackage{xeCJK}");
  });

  it("writes display maths in a name inline, and leaves out a proof idea once the kind isn't theorem-like", () => {
    const tex = toLatex(
      graphWith({
        name: "Map $$f$$",
        kind: "definition",
        anatomy: { hypotheses: [], conclusion: "c", proofIdea: "stale", examples: [], nonExamples: [], createdAt: 1 },
      }),
    );
    expect(tex).toContain("[{Map $f$}]");
    expect(tex).not.toContain("stale");
  });
});
